# Generated by Django 5.2.1 on 2025-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(blank=True, choices=[(2, 'Неудовлетварительно'), (3, 'Удовлетварительно'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
    ]
