# Generated by Django 5.2 on 2025-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='employers.teacher'),
        ),
    ]
