# Generated by Django 5.2 on 2025-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(blank=True, default='Not assigned', max_length=100, null=True),
        ),
    ]
