# Generated by Django 5.2 on 2025-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_attendance_org_grade_org_schedule_org_subject_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
