# Generated by Django 5.2 on 2025-06-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудиории'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
