# Generated by Django 5.2 on 2025-06-05 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_schedule_options_alter_schedule_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 5)),
        ),
    ]
