# Generated by Django 5.2 on 2025-06-14 11:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_subjectcolor'),
        ('schedule', '0011_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subjectcolor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 14)),
        ),
    ]
