# Generated by Django 5.2.2 on 2025-06-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_subject_color_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 15)),
        ),
    ]
