# Generated by Django 5.2 on 2025-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
