# Generated by Django 5.2 on 2025-05-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_organization_name'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='student',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
    ]
