# Generated by Django 5.2 on 2025-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(default=models.DateTimeField()),
        ),
    ]
