# Generated by Django 5.2 on 2025-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentssnapshot',
            name='date',
            field=models.DateField(),
        ),
    ]
