# Generated by Django 5.2 on 2025-06-13 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_parent_org_student_org_studentgroup_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате 8 XXX XXX XX XX ', regex='^8\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(related_name='parents', to='students.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате 8 XXX XXX XX XX ', regex='^8\\d{10}$')]),
        ),
    ]
