# Generated by Django 5.2.6 on 2025-10-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_score_accrual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrual',
            options={'verbose_name': 'Начисление баллов', 'verbose_name_plural': 'Начисления баллов'},
        ),
        migrations.AddField(
            model_name='accrual',
            name='category',
            field=models.CharField(choices=[('attendance', 'Посещаемость'), ('participation', 'Участие'), ('behavior', 'Поведение'), ('achievements', 'Достижения'), ('homework', 'Домашнее задание')], default='attendance', max_length=30, verbose_name='Категория начисления'),
        ),
        migrations.AddField(
            model_name='accrual',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
