# Generated by Django 5.2.6 on 2025-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentssnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentssnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
