# Generated by Django 5.2 on 2025-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_subscription_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(),
        ),
    ]
