# Generated by Django 5.2.6 on 2025-11-13 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('was_present', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудиории',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, choices=[(2, 'Не удовлетварительно'), (3, 'Удовлетварительно'), (4, 'Хорошо'), (5, 'Отлично')], null=True)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('grade_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('end_time', models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week_day', models.PositiveSmallIntegerField()),
                ('is_canceled', models.BooleanField(blank=True, default=False)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('duration', models.DurationField(blank=True, editable=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PeriodLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('end_time', models.TimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repeat_lessons_until_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Периодическое занятие',
                'verbose_name_plural': 'Периодические занятия',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
