# Generated by Django 5.2.6 on 2025-11-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lesson_schedule_lesson',
        ),
        migrations.AlterModelTable(
            name='periodlesson',
            table='lesson_schedule_periodlesson',
        ),
    ]
