# Generated by Django 5.2 on 2025-08-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0002_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
