# Generated by Django 5.2 on 2025-08-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0003_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='lesson_date',
        ),
    ]
