# Generated by Django 5.2 on 2025-08-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0004_rename_date_attendance_lesson_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='lesson_date',
            new_name='date',
        ),
    ]
