# Generated by Django 5.2 on 2025-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0006_rename_date_attendance_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
