# Generated by Django 5.2 on 2025-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0007_grade_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='date',
            new_name='grade_date',
        ),
    ]
