# Generated by Django 5.2 on 2025-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_schedule', '0008_rename_date_grade_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
