# Generated by Django 5.2 on 2025-07-01 13:14

import mainapp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='repeat_lessons_until',
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='repeat_lessons_until',
            field=mainapp.fields.MonthDayField(default='08-31', max_length=5),
        ),
    ]
