# Generated by Django 5.2 on 2025-05-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='org',
        ),
    ]
