# Generated by Django 5.2 on 2025-08-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_usersettings_repeat_lessons_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
