# Generated by Django 5.2.6 on 2025-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_usersettings_options_organization_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
