# Generated by Django 5.2 on 2025-06-14 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Неверный формат цвета', regex='^#\\d{6}$')])),
            ],
            options={
                'verbose_name': 'Цвет предмета',
                'verbose_name_plural': 'Цвета предметов',
            },
        ),
    ]
