# Generated by Django 5.2 on 2025-06-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_subjectcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcolor',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
    ]
