# Generated by Django 5.2 on 2025-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_subjectcolor_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcolor',
            name='color_hex',
            field=models.CharField(max_length=7),
        ),
    ]
