# Generated by Django 5.2 on 2025-06-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_subjectcolor_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcolor',
            name='color_hex',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Неверный формат цвета', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
