# Generated by Django 5.2 on 2025-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_subjectcolor_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcolor',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
