# Generated by Django 5.2 on 2025-05-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('mainapp', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organization'),
        ),
    ]
