# Generated by Django 5.2 on 2025-09-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': 'Запросы на отпуск', 'verbose_name_plural': 'Запросы на отпуск'},
        ),
    ]
