# Generated by Django 5.2 on 2025-05-31 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_org_jobtitle_org_leaverequest_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employers.employer'),
        ),
    ]
