# Generated by Django 5.2.6 on 2025-10-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_teachernote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachernote',
            old_name='teacher',
            new_name='teacher_profile',
        ),
    ]
